#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
export NEW_RELIC_LOG_ENABLED=false
echo "This is the setup script"

#export NRIA_ENABLE_PROCESS_METRICS=true
exit 0
