#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 

export NODE_ENV=development

cd /root/java-tutorials-app/Tutorials/ClientApp

# setup frontend local env file
cp .env.example .env.local
