#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"


if [ -z "$(systemctl | grep newrelic-infra.service)" ]; then
  echo "Service not found"
  exit 1
else
  echo "Service has been installed and is active"
  exit 0
fi