#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 

export NODE_ENV=development

cd /root/pern-newrelic/packages/frontend

#switch to the branch `instruqt`
# git checkout instruqt

# Install required npm packages for the app
cd /root/pern-newrelic

#switch to the branch `instruqt`
# git checkout instruqt

npm run install:frontend

cd /root/pern-newrelic/packages/frontend
cp .env.example .env.local